[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
    "chimera/=lib/chimera/src/",
    "ds-test/=lib/solmate/lib/ds-test/src/",
    "setup-helpers/=lib/setup-helpers/src/",
    "@chimera/=lib/chimera/src/",
    "@recon/=lib/setup-helpers/src/",
    "properties/=lib/properties/contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
