[profile.default]
src = "src"
out = "out"
libs = ["lib"]
coverage_include = ["src/**", "lib/solmate/src/**"]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[invariant]
corpus_dir = "invariant-corpus"
